### PR TITLE
Change "Make a request" button (list view) to full width

### PR DESCRIPTION
**Pull request by forevermatt**

### CODE REVIEW

**Comment by forevermatt** [comment]
Before: 
Screen Shot 2020-03-20 at 1 44 52 PM

After: 
Screen Shot 2020-03-20 at 1 44 23 PM

**Comment by wcjr** [comment]
image

looks funny to me a little.... without making it `btn-sm`
image

also, this seems more declarative to me but you can decide which you prefer @forevermatt :

```
      <button on:click={() => push('/requests/new')} class="btn btn-success w-100"><span style="font-size: larger">+</span> Make a request</button>

```

**Comment by forevermatt** [comment]
Those suggestions seem fine to me, @wcjr. I'll push up another commit.

**Comment by forevermatt** [comment]
Using a button also gives us the benefit of letting the user get to it via Tabbing.

**Pull request merged**
